### ISSUE TITLE
Does it support other platforms

### ISSUE THREAD

**Issue by nozomanai** [JanSeliv/PoolManager#9]
At present, plugins must use Binaries files downloaded from the repository. Deleting the Binaries file and opening the project for UE compilation will result in an message:
![image](https://github.com/user-attachments/assets/1d7be9ca-a1a3-48a4-81f4-4e5aba34b349)

Can I package it myself and support other platforms?

**Comment by JanSeliv** [comment]
@nozomanai Thank you for raising the issue.

All platforms are supported and have been tested on Windows, macOS, Linux, and Android.

The included binaries are precompiled only for Windows (currently for UE5.4). For other platforms, you'll need to compile them yourself.

The error suggests that no binaries were found: it seems the folder was removed, but new binaries weren't compiled, so the folder is likely empty on your end.

If you'd like further assistance, feel free to join our Discord and bring this up in the **pool-manager** channel. I'll be happy to help and respond more quickly there.

http://dsc.gg/BigJanStudio
